Move alerts to header component
equinor/flotilla pull request #1018
Opened 2023-09-21 11:47 UTC by andchiind

Closes #1008

2023-09-25 11:35 UTC, andchiind commented
As a part of implementing the alert in such a way that the dialog closes itself when an error is returned, I ended up refactoring MissionQueueView.tsx and the dialog component file.

2023-10-10 13:24 UTC, Eddasol commented
![image](https://github.com/equinor/flotilla/assets/33518988/2d45978a-658c-45fc-b78d-39890b4e0e5d)
![image](https://github.com/equinor/flotilla/assets/33518988/8d87167d-a7ef-40b8-82e3-8070236d65ac)
Gap between "Add mission" and "Create mission" changes when "Add mission" is pressed

2023-10-11 07:11 UTC, Eddasol commented on frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx
>      const { installationCode } = useInstallationContext()
Set the contexts together at line 46 to 49 for better structure

2023-10-13 08:58 UTC, andchiind commented
> ![image](https://user-images.githubusercontent.com/33518988/273920704-47812701-bc30-42b4-8a18-527d70abebe5.png) Suggest updating style in "Request error" to match existing style for failed mission

I've now made them as similar as possible without changing the information.

2023-10-13 08:59 UTC, andchiind commented
> ![image](https://user-images.githubusercontent.com/33518988/273915589-2d45978a-658c-45fc-b78d-39890b4e0e5d.png) ![image](https://user-images.githubusercontent.com/33518988/273915852-8d87167d-a7ef-40b8-82e3-8070236d65ac.png) Gap between "Add mission" and "Create mission" changes when "Add mission" is pressed

This should be fixed now.

2023-10-23 08:58 UTC, mrica-equinor requested changes

2023-10-23 14:38 UTC, andchiind commented on frontend/src/App.tsx
> +                <LanguageProvider>
The order matters in the sense that if you want to use a context, the component/context that uses it needs to be within the provider of the context you're using. So for MissionsProvider to use the alerts, AlertProvider needs to envelop it.

2023-10-30 15:04 UTC, andchiind commented on frontend/src/components/Alerts/FailedMissionAlert.tsx
> +        <Button as={Typography} onClick={goToMission} variant="ghost" color="secondary">
sorry but I don't suppose you remember the name of that colour?

2023-11-07 12:14 UTC, andchiind commented on frontend/src/components/Alerts/FailedMissionAlert.tsx
> +        <Button as={Typography} onClick={goToMission} variant="ghost" color="secondary">
I don't see it in EDS 
![image](https://github.com/equinor/flotilla/assets/20266900/46677e53-b705-4a24-ae97-21b7ff17e1b3)

2023-11-10 10:59 UTC, andchiind commented on frontend/src/components/Alerts/FailedMissionAlert.tsx
> +        <Button as={Typography} onClick={goToMission} variant="ghost" color="secondary">
Done

2023-11-10 12:18 UTC, mrica-equinor approved these changes
LGTM :)

2023-11-10 13:23 UTC, merged