Improve send robots to safe zone during localization mission
equinor/flotilla pull request #1470
Opened 2024-03-13 12:12 UTC by mrica-equinor

Closes #1461

2024-03-14 12:44 UTC, andchiind approved these changes
Haven't managed to make it fail, LGTM

2024-03-15 09:17 UTC, oysand commented on backend/api/EventHandlers/MissionEventHandler.cs
> +                if (await MissionService.OngoingLocalizationMissionRunExists(missionRun.Robot.Id))
Can this be combined with pending above?

2024-03-15 09:24 UTC, oysand commented on backend/api/EventHandlers/MissionEventHandler.cs
> +            return area ?? null;
```suggestion
            var area = await AreaService.ReadById(robot.CurrentArea!.Id);
            if (area == null)
            {
                _logger.LogError("Could not find area with ID {AreaId}", robot.CurrentArea!.Id);
                SignalRService.ReportSafeZoneFailureToSignalR(robot, $"Robot {robot.Name} was not correctly localised. Could not find area {robot.CurrentArea.Name}");
                return null;
            }
            return area;
```

2024-03-19 07:36 UTC, oysand approved these changes
LGTM

2024-03-19 07:37 UTC, oysand requested changes
Woops, added for wrong PR. Still need the tests discussed

2024-03-21 06:42 UTC, oysand commented on backend/api/EventHandlers/MissionEventHandler.cs
> +            var area = await FindRobotArea(robot.Id);
Currently it is abit unclear from the name that this function also checks what area the robot will be localized in, could the name be more explicit? Something along the lines of FindCurrentRobotAreaOrTheOneItWillBeLocalizedIn, just better formulated?

2024-03-21 06:43 UTC, oysand commented on backend/api/EventHandlers/MissionEventHandler.cs
> +            var area = await FindRobotArea(robot.Id);
Maybe FindRelevantRobotAreaForSafePositionMission?

2024-03-21 09:09 UTC, oysand commented on backend/api/EventHandlers/MissionEventHandler.cs
> +                if (await MissionService.OngoingLocalizationMissionRunExists(robotId))
Should we also check for pending localization mission?

2024-03-21 14:57 UTC, tsundvoll approved these changes

2024-03-22 10:58 UTC, oysand approved these changes
LGTM

2024-03-22 11:02 UTC, merged