Improve mission page
equinor/flotilla pull request #1848
Opened 2024-12-05 08:40 UTC by mrica-equinor

2024-12-06 08:41 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
> +    }
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/b41b3103-6dd8-4bdc-8838-56972604c0eb">
Should info section be same width as rest? Also it doesn't seem centered with regards to height

2024-12-06 08:55 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
>  const TitleSection = styled.div`
Suggest putting the "Add to queue"-button under the title on smal screen (maybe flex: wrap?)
<img width="343" alt="image" src="https://github.com/user-attachments/assets/868b19fd-6182-407a-bd41-b2652ec78918">

2024-12-06 08:57 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
> +                    <Table.Cell>#</Table.Cell>
Consider using different design for task table on small screen
<img width="330" alt="image" src="https://github.com/user-attachments/assets/ed8102af-1227-45de-8135-b082952bfde0">

2024-12-06 11:02 UTC, Eddasol commented on frontend/src/utils/DeckMapView.tsx
> +import { getMeta } from 'components/Pages/MissionPage/MapPosition/MissionMapView'
Should getMeta be in utils instead since its used by both? Maybe in a map utilities file (in a map folder?)?

2024-12-06 11:02 UTC, Eddasol commented on frontend/src/utils/DeckMapView.tsx
> +import { getMeta } from 'components/Pages/MissionPage/MapPosition/MissionMapView'
Or maybe not since deckMapView probably will disappear soon

2024-12-06 11:20 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/MissionPage.tsx
> +    min-height: 60%;
These values feel a bit arbitrary. Are they necessary?

Look at ContainButton for missionHistoryButton for inspiration

2024-12-12 10:46 UTC, eivindsjovold requested changes
Re-run snyk checks

2025-01-08 09:42 UTC, mrica-equinor commented on frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
> +                    <Table.Cell>#</Table.Cell>
Think this can be done in a different PR as improvement

2025-01-08 09:43 UTC, mrica-equinor commented on frontend/src/components/Pages/MissionPage/MissionPage.tsx
> +    min-height: 60%;
This has been replaced with just min-height: 60%;

2025-01-08 12:03 UTC, Eddasol commented on frontend/src/components/Header/Header.tsx
> +    height: fit-content;
Queue mission button becomes squashed

Before:
<img width="469" alt="image" src="https://github.com/user-attachments/assets/11ccbffa-cc23-4a9e-8cfb-5aa5ae3978fd" />
In this PR:
<img width="450" alt="image" src="https://github.com/user-attachments/assets/49377c6f-ff35-41bb-a2be-277bb1947785" />

2025-01-08 12:05 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/MissionPage.tsx
> +
Remove

2025-01-08 12:08 UTC, eivindsjovold submitted a review, later dismissed

2025-01-08 12:09 UTC, Eddasol commented on frontend/src/components/Displays/MissionButtons/MissionRestartButton.tsx
> +    height: fit-content;
Queue mission button becomes squashed

Before:
<img width="469" alt="image" src="https://github.com/user-attachments/assets/11ccbffa-cc23-4a9e-8cfb-5aa5ae3978fd" />
In this PR:
<img width="450" alt="image" src="https://github.com/user-attachments/assets/49377c6f-ff35-41bb-a2be-277bb1947785" />

2025-01-08 12:09 UTC, eivindsjovold reviewed
snyk ok

2025-01-08 12:16 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
> +        <StyledTable>
Not necessary to solve in this PR but consider utilizing the available room on the right for the task table

<img width="446" alt="image" src="https://github.com/user-attachments/assets/d382e2fb-eaae-4766-a8c1-7b5e4f51cb08" />

2025-01-08 12:21 UTC, Eddasol commented on frontend/src/components/Pages/FrontPage/FrontPage.tsx
> +    min-height: calc(100vh - 65px);
What is the purpose of this part?

2025-01-08 12:23 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/MapPosition/MissionMapView.tsx
> +        </>
Remove unnecessary <> wrapper

2025-01-08 12:25 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
> +    @media (max-width: 600px) {
Is it intentional that max width here is 600 and on the next style (line 53) its 500?

2025-01-08 12:28 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
> +    padding: 10px 10px 10px 10px;
Wouldn't this be the same as just saying padding: 10px?
```suggestion
    padding: 10px;
```

2025-01-08 12:34 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/MissionPage.tsx
> +const StyledMissionPageCardsWidth = styled.div`
```suggestion
const StyledCardsWidth = styled.div`
```
Seems redundant to include the file name in the style name

2025-01-08 12:36 UTC, Eddasol commented on frontend/src/components/Pages/MissionPage/MissionPage.tsx
> +                        </StyledMissionPageContent>
The <> wrapper around this can be removed

2025-01-09 08:33 UTC, mrica-equinor commented on frontend/src/components/Pages/MissionPage/MissionPage.tsx
> +    min-width: 50%;
This is what keeps the card with the status, area, etc with the same min-width as the card around the table, otherwise would be smaller than the card around the table (and map)

2025-01-09 08:51 UTC, mrica-equinor commented on frontend/src/components/Pages/FrontPage/FrontPage.tsx
> +    min-height: calc(100vh - 65px);
&5px is the height of the header i think.  This amkes the fron page background gray, if it was 100vh then you would be able to scroll down the 65px from the header which i found annoying. This way the front page height is exactly the size of your vertical screen

2025-01-09 08:52 UTC, mrica-equinor commented on frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
> +    @media (max-width: 600px) {
Good catch, thank you

2025-01-10 08:13 UTC, andchiind approved these changes
Looks good. Tested it and did not find any bugs on desktop or phone.

2025-01-10 08:20 UTC, merged

2025-01-13 07:39 UTC, Eddasol commented on frontend/src/components/Pages/FrontPage/FrontPage.tsx
> +    min-height: calc(100vh - 65px);
It its the size of the top bar it could be better to use a variable. Maybe take inspiration from this line in InspectionTable.tsx:

`const topBarHeight = document.getElementById(FrontPageSectionId.TopBar)?.offsetHeight ?? 0`