Add mission scheduler
equinor/flotilla pull request #231
Opened 2022-06-10 11:08 UTC by oysand

2022-06-10 12:21 UTC, GodVenn requested changes
Please see comments

2022-06-10 12:21 UTC, GodVenn commented on backend/api/Services/ScheduledMissionService.cs
> +        public async Task<List<ScheduledMission>> UpcomingPendingScheduledMissions()
Renaming suggestion
```suggestion
        public async Task<List<ScheduledMission>> GetUpcomingPendingScheduledMissions()
```

2022-06-10 12:25 UTC, oysand commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +                        if (upcomingScheduledMission.StartTime > DateTimeOffset.UtcNow) { break; }
They are ordered by time

2022-06-13 06:26 UTC, oysand commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +                        if (startedSuccessfull) { UpdateUpcomingScheduledMissions(); }
Agreed

2022-06-13 06:26 UTC, oysand commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +            catch (ArgumentNullException)
Agreed, I think we should not tolerate this

2022-06-13 06:29 UTC, oysand commented on backend/api/Services/ScheduledMissionService.cs
> +        public async Task<List<ScheduledMission>> UpcomingPendingScheduledMissions()
Agreed

2022-06-13 06:29 UTC, oysand commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +                if (robot == null) return false;
Agreed

2022-06-13 09:39 UTC, oysand commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +        private async Task<bool> StartScheduledMission(ScheduledMission scheduledMission)
Agreed

2022-06-13 09:39 UTC, oysand commented on backend/api/Services/ScheduledMissionService.cs
> +            return pendingScheduledMissions.OrderBy(ev => ev.StartTime).ToList();
Agreed

2022-06-15 11:20 UTC, GodVenn commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +                _logger.LogInformation("Robot {id} is not available", scheduledMission.Robot.Id);
```suggestion
                _logger.LogWarning("Robot {id} is not available", scheduledMission.Robot.Id);
```

2022-06-16 05:51 UTC, oysand commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +                _logger.LogInformation(e, "Failed to start mission {id}", scheduledMission.Id);
Agreed

2022-06-16 05:51 UTC, oysand commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +                _logger.LogInformation("Robot {id} is not available", scheduledMission.Robot.Id);
Agreed

2022-06-16 05:51 UTC, oysand commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +                _logger.LogInformation("Could not find robot {id}", scheduledMission.Robot.Id);
Agreed

2022-06-16 05:52 UTC, oysand commented on backend/api/EventHandlers/ScheduledMissionEventHandler.cs
> +                        if (startedSuccessfull) { UpdateUpcomingScheduledMissions(); }
It was added below. Will update the log level to LogWarning

2022-06-16 07:05 UTC, GodVenn approved these changes
LGTM

2022-06-16 09:38 UTC, merged