Backend dockerfile
equinor/flotilla pull request #62
Opened 2022-02-03 09:09 UTC by yamikarajput546

added Dockerfile and update docker-compose.yml

2022-02-04 07:39 UTC, aestene commented on backend/Dockerfile
> +CMD ["gunicorn", "--bind", "127.0.0.1:8000", "src/flotilla/main.py"]`
```suggestion
CMD ["gunicorn", "--bind", "127.0.0.1:8000", "src/flotilla/main.py"]

```
Also remember to add a newline at the end of this file.

2022-02-04 07:42 UTC, aestene commented on backend/Dockerfile
> +RUN  pip install gunicorn
```suggestion
RUN pip install gunicorn
```

2022-02-04 07:43 UTC, aestene commented on backend/Dockerfile
> +FROM python:latest
```suggestion
FROM python:3.9
```
We have not upgraded to python 3.10 here so it would be best if the docker image is based on python 3.9

2022-02-04 08:11 UTC, yamikarajput546 commented
hey @oysand i've updated the Dockerfile please review :)

2022-02-04 08:33 UTC, aestene commented on backend/Dockerfile
> +CMD ["gunicorn", "--bind", "127.0.0.1:8000", "src/flotilla/main.py"]
```suggestion
CMD ["uvicorn", "--host", "0.0.0.0", "src.flotilla.main:app"]
```
We'd prefer to use `uvicorn` for the time being. Also, you have to bind to `0.0.0.0` within the container for the application to be available through the port mapping in `docker-compose.yml`

2022-02-04 08:35 UTC, aestene commented on backend/Dockerfile
> +RUN pip install gunicorn
```suggestion
```
This may be removed when using `uvicorn` and `uvicorn` is installed in the dependencies already.

2022-02-04 08:37 UTC, aestene commented
Hi @yamikarajput546! Thanks for the contribution :)

You were so quick I didn't have time to finish the last review. I had some issue making the application run with Docker as there were some import issues. I've made one comment now which moves to `uvicorn` but also fixes this. 

Finally, I'd like you to squash your commit history into one commit and have that commit message abide by [these guidelines](https://cbea.ms/git-commit/). For you a commit message could be `Add Dockerfile for backend application`

2022-02-04 08:37 UTC, aestene requested changes
See the comment above.

2022-02-14 10:02 UTC, aestene approved these changes
LGTM

2022-02-14 10:05 UTC, aestene commented
Hi @yamikarajput546!

As we are planning to use this functionality soon I took the liberty to finish the remaining points on the review. Thank you for the contribution :tada:

2022-02-14 10:05 UTC, merged

2022-02-14 10:58 UTC, yamikarajput546 commented
hey @aestene 
I really appreciate and thank you also for merging, In the future, you need help to dockerize let me know :)