Use single except catch in controllers
equinor/flotilla pull request #82
Opened 2022-02-10 08:52 UTC by vetlek

Closes #78 and #74

2022-02-10 13:16 UTC, anetteu requested changes
Good work!

2022-02-10 13:53 UTC, anetteu submitted a review, later dismissed

2022-02-10 14:38 UTC, vetlek commented on backend/src/flotilla/api/missions_api.py
> +                continue
Feel that the deserializing to the mission format used in the API should be independent from the EchoService, which only is used to contact Echo.

2022-02-10 15:01 UTC, nicholasdalhaug requested changes

2022-02-11 08:02 UTC, vetlek commented on backend/src/flotilla/api/missions_api.py
> +                continue
Done

2022-02-11 08:16 UTC, nicholasdalhaug approved these changes
🎉

2022-02-11 08:24 UTC, merged