Link state of mission control buttons
equinor/flotilla pull request #820
Opened 2023-05-30 13:33 UTC by andchiind

2023-06-02 07:16 UTC, phhuseboe commented on flotilla.code-workspace
I think this file can be removed

2023-06-02 12:41 UTC, phhuseboe commented on frontend/src/components/Contexts/MissionControlContext.tsx
> +}
ControlButton is already defined in MissionControlButtons.tsx, so we could consider to import it from there

2023-06-09 09:31 UTC, Christdej requested changes

2023-06-09 09:31 UTC, Christdej commented on frontend/src/components/Contexts/MissionControlContext.tsx
> +                //.catch((e) => handleError(e))
Even if you just move the function, I think we can remove the comment

2023-06-09 09:31 UTC, Christdej commented on frontend/src/components/Contexts/MissionControlContext.tsx
> +                //.catch((e) => handleError(e))
Even if you just move the function, I think we can remove the comment

2023-06-09 09:31 UTC, Christdej commented on frontend/src/components/Contexts/MissionControlContext.tsx
> +                //.catch((e) => handleError(e))
Even if you just move the function, I think we can remove the comment

2023-06-09 09:31 UTC, Christdej commented on frontend/src/App.tsx
> +                {/* // <ErrorBoundary fallbackRender={({ error, resetErrorBoundary }) => ErrorFallback(error)}> */}
I think we can remove the comment

2023-06-16 16:04 UTC, Christdej approved these changes
LGTM

2023-06-19 07:16 UTC, merged