Add ObstacleDected to Robot in backend
equinor/flotilla pull request #989
Opened 2023-08-30 06:14 UTC by UsamaEquinorAFK

2023-09-19 09:53 UTC, oysand commented on backend/api/Database/Models/Robot.cs
> +        public bool? ObstacleDectected { get; set; }
Is this a bit specific to add it as a column to the robot table? Is there a more general status object we want to use instead?

2023-09-19 10:08 UTC, oysand requested changes
Consider handling obstacle status as part of robot status

2023-09-19 11:03 UTC, UsamaEquinorAFK commented
> Consider handling obstacle status as part of robot status

I thought about this I would like to keep the ObstacleStatus as a seperate entity in robot table in Database. It can be used in the future to pin point the obstacle location on the map by changing the message we send from isar-taurob in the future and that would be a very cool functionality to have in the future. Let me know what you think ?? :) 

I agree with sending the robot_status from isar and that can be implemented seperately. I can write up a issue link and work on that it in parallel.

2023-09-20 07:06 UTC, oysand commented
> > Consider handling obstacle status as part of robot status
> 
> I thought about this I would like to keep the ObstacleStatus as a seperate entity in robot table in Database. It can be used in the future to pin point the obstacle location on the map by changing the message we send from isar-taurob in the future and that would be a very cool functionality to have in the future. Let me know what you think ?? :)
> 
> I agree with sending the robot_status from isar and that can be implemented seperately. I can write up a issue link and work on that it in parallel.

I think is better to keep the implementation now as simple as possible tailored to the current issue and not have ObstacleStatus as part of the robot table. In general preparing for future implementations can be good, but this would add complexity to the system and we would need to ensure that ObstacleStatus is correctly set with regards to the robot status. 

If this is needed for obstacle location in the map I think we should wait with implementing this until we implement that feature.

2023-10-11 11:26 UTC, Eddasol commented
Covered by a different PR

2023-10-11 11:26 UTC, closed without merging